version: 2.1

orbs:
  linter: talkiq/linter@4

executors:
  python:
    docker:
      - image: python:3.11.9
    resource_class: small

workflows:
  run-tests:
    jobs:
      - linter/pre-commit:
          executor: python
